### PR TITLE
Display next steps input box in same line

### PR DESCRIPTION
**Pull request by gopar**
**Description of change**
In the Next Steps page, allow a user to edit their entry in-place instead of allowing them to edit the entry in the bottom of the list

**How to test**
Pull down changes
Start/edit a report and go to next steps
Once you enter a few items, you can select "Edit" from context menu.
You should be able to edit the entry right there

**Issue(s)**
* https://github.com/HHS/Head-Start-TTADP/issues/397

**Checklist**

- [x] Meets issue criteria
- [x] Code tested
- [x] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] Documentation updated
    - API methods
    - Boundary and Data Flow Diagrams
    - [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
    - OSCAL templates completed when security controls are implemented or modified

### CODE REVIEW

**Comment by gopar** [comment]
I wanted to add focus to the entry box when component is visible but for some reason I couldn't get it to work? That wasn't necessary in scope but it would of been a nice thing to add.

**Comment by gopar** [comment]
> This is definitely a nice improvement!
> 
> While looking at it, I noticed a small bug with the next steps - something it appears we have in prod as well. When entering next steps with the same name, the "edit" functionality gets confused and leaves extra display. To reproduce:
> 
> * enter next step - "test1"
> * enter second next step - "test2"
> * click "edit" for "test1"
> * change the name to be "test2"
> * change the first "test2" back to "test1"
> * observe the UI

Ah yes, the issue there is that when iterating through the items, I'm using the items `note` as the key (you can't use the items index for specific reasons) so when one or more are identical it can get funky. I wagered on notes being distinct enough that we wouldn't have this corner case. 

I'll see if I can use something else instead as the key (currently I only have 2 choices, the contents or the index and cant use index.) I might swtich to adding a default timestamp to each entry to keep track that way

**Comment by gopar** [comment]
Ended up using both note test with index to create unique key. That seems to solve the issue

**Review by kryswisnaskas — APPROVED** [review]
Looks good!

**Review by jasalisbury — APPROVED** [review]
:rocket:

**Review by rahearn — APPROVED** [review]
Awesome

**Pull request merged**
