### PR TITLE
Cm 363 record deployments

### PR DESCRIPTION
**Pull request by dcmcand**
**Description of change**
Adds logging deployements to new relic

**How to test**
Force a deploy to sandbox, make sure deploy shows up in new relic.

I tested it and the deploy did show up.

Screenshot from 2021-03-12 09-36-44

**Issue(s)**
* https://github.com/HHS/Head-Start-TTADP/issues/363

**Checklist**

- [X] Meets issue criteria
- [X] Code tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] Documentation updated
    - API methods
    - Boundary and Data Flow Diagrams
    - [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
    - OSCAL templates completed when security controls are implemented or modified

### CODE REVIEW

**Review by jasalisbury — APPROVED** [review]

**Comment by kryswisnaskas** [comment]
How many recent deploys are going to show on the list? Is there a limit?

**Comment by dcmcand** [comment]
> How many recent deploys are going to show on the list? Is there a limit?

I am not sure, the documentation is unclear.

**Comment by dcmcand** [comment]
> How many recent deploys are going to show on the list? Is there a limit?

I am not sure, the documentation is unclear.

**Review by kryswisnaskas — APPROVED** [review]
Thanks for putting that in. It will come in handy!

**Pull request closed without merging**
