### PR TITLE
Saving activity report - frontend

### PR DESCRIPTION
**Pull request by jasalisbury**
**Description of change**
Can save an activity report on the frontend

 * Reports are saved anytime a user navigates to a new page
 * Reports are automatically saved every 2 minutes (separate timer from the save on navigation)
 * New reports are created, previously created reports are updated on save
 * Multiselects can handle objects in addition to strings
 * Names of fields updated to match database field names
 * Last save time displayed under the stickied report navigator
 * Previously saved reports can be viewed by entering their id in the path of the url (`/activity-reports/{id}...`)

**How to test**

1) Browse to [sandbox](https://tta-smarthub-sandbox.app.cloud.gov/activity-reports/new)
2) Start filling out a report (you have to fill out at least one grant or nonGrantee for the report to save)
3) Pull up the console and switch pages of the report, note the id of the saved report
4) Browse to `https://tta-smarthub-sandbox.app.cloud.gov/activity-reports/{id}/activity-summary` (fill in the id from previous step)
5) Note the info you previously entered is populated in the report

The only fields that do not save are the file upload fields and `collaborating users`.

**Issue(s)**
* https://github.com/HHS/Head-Start-TTADP/issues/98
* https://github.com/HHS/Head-Start-TTADP/issues/163

**Checklist**

- [x] Meets issue criteria
- [x] Code tested
- [x] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [x] Documentation updated
    - API methods
    - Boundary and Data Flow Diagrams
    - [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
    - OSCAL templates completed when security controls are implemented or modified

### CODE REVIEW

**Review by dcmcand — COMMENTED** [review]
Tested and everything works as described.

Are you planning on future changes to update the url after it saves (change form /activity-report/new to /activity-report/$REPORTID)?

**Review by kryswisnaskas — COMMENTED** [review]
Fantastic work! 🎉 

Couple of questions and comments:

Is the plan to use the group feature from `react-select` for the Grants/Grantee display to match the design? Or did we clear with Aricka that we won't be showing the grouping with bold grantee names for the MVP?

I noticed that the `ids `of `ActivityParticipants `db table change on every save. Is that intended?

**Comment by jasalisbury** [comment]
> I noticed that the `ids `of `ActivityParticipants `db table change on every save. Is that intended?

Yeah that is because when an activity report is saved all `activity-participants` are removed and the currently selected `activity-participants` added back to the activity report. We could be smarter about removing only `activity-participants` that have been removed from the list and adding only new `activity-participants` but the current way it works is simpler.

**Comment by jasalisbury** [comment]
> Tested and everything works as described.
> 
> Are you planning on future changes to update the url after it saves (change form /activity-report/new to /activity-report/$REPORTID)?

Yeah I tried for a little while to update the URL but coudn't get it to update properly without a page reload. I'll probably revisit at some point in the future. In the meantime the `reportId` could definitely make it down as a prop.

**Comment by jasalisbury** [comment]
> Is the plan to use the group feature from `react-select` for the Grants/Grantee display to match the design? Or did we clear with Aricka that we won't be showing the grouping with bold grantee names for the MVP?

I just pushed up a change that should group grants by grantee.

**Review by dcmcand — APPROVED** [review]

**Comment by kryswisnaskas** [comment]
One other comment I forgot to mention was that the browser navigation seemed to have changed when trying to get to "Home" from "ActivityReports" using the browser's back button. The other way it worked perfectly fine. You could always got from "Home" to "ActivityReports". I am fine with merging this PR, but keeping in mind that might be something to re-visit.

**Comment by kryswisnaskas** [comment]
The grouping of the grantees looks great, btw!

**Pull request merged**
