### PR TITLE
Use new staging users

### PR DESCRIPTION
**Pull request by jasalisbury**
## Description of change

Seed staging users

## How to test

Verify you can login to ~staging~ sandbox without requesting permissions

### CODE REVIEW

**Review by thewatermethod — DISMISSED** [review]
👍

**Comment by thewatermethod** [comment]
Wait, is this for staging or sandbox?

**Comment by jasalisbury** [comment]
> Wait, is this for staging or sandbox?

It uses the new HSES staging users. We use HSES staging in `dev` `staging` and `sandbox`.

**Comment by thewatermethod** [comment]
Gotcha. Sorry, to be clear, I was asking about this line in **How to Test**

> Verify you can login to staging without requesting permissions

I was asking testing about sandbox v staging

I verified the seeders ran locally but obviously no permissions on sandbox.

So are we proceeding with this approach, given we have to run it via ssh?

**Comment by jasalisbury** [comment]
> Gotcha. Sorry, to be clear, I was asking about this line in **How to Test**
> 
> > Verify you can login to staging without requesting permissions
> 
> I was asking testing about sandbox v staging
> 
> I verified the seeders ran locally but obviously no permissions on sandbox.
> 
> So are we proceeding with this approach, given we have to run it via ssh?

Yeah sorry I was talking about sandbox, not staging. And it isn't working because I forgot I removed seeders from running on deploys to sandbox like 3 months ago. I can't SSH into sandbox for some reason and was just going to try again Monday to run the seeders

**Comment by jasalisbury** [comment]
After thinking about this a bit it seems like most users are getting added to sandbox/staging. It is nice having persisted data in sandbox/dev so we can test out migrations with "real" data sitting in the database. I think this PR is fine as is not being ran against sandbox. If we ever do reset sandbox users will be added from the seeders, but I don't see much of a reason to run the seeders right now just to apply these changes.

**Review by thewatermethod — APPROVED** [review]
Ok cool - I was able to run it locally.

**Pull request merged**
