### PR TITLE
Logical data model

### PR DESCRIPTION
**Pull request by rahearn**
**Description of change**

Adding a logical data model markdown file that stores the PlantUML version of the entity relationship diagram, rendered version of the diagram, and link to how to update it.

**How to test**
N/A

**Issue(s)**
* https://github.com/HHS/Head-Start-TTADP/issues/58

**Checklist**

- [x] Meets issue criteria
- [x] Documentation updated
    - API methods
    - Boundary and Data Flow Diagrams
    - [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
    - OSCAL templates completed when security controls are implemented or modified

Open question. Would you all like me to write an ADR around the use of plantuml? I don't feel it's necessary since it's not impacting the actual system, but will write one if you'd prefer.

### CODE REVIEW

**Review by jasalisbury — COMMENTED** [review]
Is there a way to mark fields as `NOT NULL`? `id` `createdAt` and `updatedAt` are all not nullable

**Comment by rahearn** [comment]
> Is there a way to mark fields as `NOT NULL`

Technically by the UML spec we should be setting nullable fields as having a [0..1] multiplicity option. Here's that diagram implemented that way: http://www.plantuml.com/plantuml/uml/RSsnIWH13CRnVfuYdI3SeQqSnrdQs5c9HMxdStTmaXcIh8U8x-vilqsAtpyX5m-sMAMcE-BlLZ9rQzSASRgLM8XrhiWqMRivVGAH_AjePsEXMXJnqq7DOcafJPNTwSrXz9k8xgbaUgAYWNdGwJH3OHp8v_F8XyCOYyEtWvTjqyEAplJ-S3m-VeoeBDZXlZJ5wofNs4w5SAaxFXcsryynMXI11qiVllQyut_f0ishr7y0

Do you prefer that, or worse?

**Comment by jasalisbury** [comment]
> > Is there a way to mark fields as `NOT NULL`
> 
> Technically by the UML spec we should be setting nullable fields as having a [0..1] multiplicity option. Here's that diagram implemented that way: http://www.plantuml.com/plantuml/uml/RSsnIWH13CRnVfuYdI3SeQqSnrdQs5c9HMxdStTmaXcIh8U8x-vilqsAtpyX5m-sMAMcE-BlLZ9rQzSASRgLM8XrhiWqMRivVGAH_AjePsEXMXJnqq7DOcafJPNTwSrXz9k8xgbaUgAYWNdGwJH3OHp8v_F8XyCOYyEtWvTjqyEAplJ-S3m-VeoeBDZXlZJ5wofNs4w5SAaxFXcsryynMXI11qiVllQyut_f0ishr7y0
> 
> Do you prefer that, or worse?

I _think_ I like having `[0..1]` but if you didn't state `[0..1]` on a field means it is nullable I probably wound't have figured it out. Could go either way on if we should add it or not, whatever you think is fine.

**Review by jasalisbury — APPROVED** [review]

**Comment by rahearn** [comment]
@jasalisbury I think this update gets us to a good place of having the info and not getting into esoteric UML features.

**Comment by kryswisnaskas** [comment]
> Open question. Would you all like me to write an ADR around the use of plantuml? I don't feel it's necessary since it's not impacting the actual system, but will write one if you'd prefer.

I think it might be nice to have a short ADR if you don't mind. If it becomes too much of a burden we could skip it.

**Comment by kryswisnaskas** [comment]
Overall, it looks good. Thanks.

**Pull request merged**
