### PR TITLE
Header, SiteNav, logos, icons

### PR DESCRIPTION
**Pull request by dcloud**
**Description of change**

Created a SiteNav that lives on the left of the page, per the design. Moved navigation elements from the header to the SiteNav. The header is now just the logo and website title. 

I made the SiteNav and Header match the design as closely as possible, but the links near the bottom of the SiteNav are a lighter than the design because the gray didn't pass accessibility requirements around color contrast.

I also added some classes to `<body>` since it seemed we want some base font/text-color styles as the default. I had noticed some elements were rendering with system fonts rather than those from the DS.

Since I was working on the logo, I also created icons for the app manifest and favicons, and updated the meta description to match the title of the application.

**How to test**

**Issue(s)**
* https://github.com/HHS/Head-Start-TTADP/issues/86
* https://github.com/HHS/Head-Start-TTADP/issues/93

**Checklist**

- [x] Meets issue criteria
- [x] Code tested
- [x] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] Documentation updated
    - API methods
    - Boundary and Data Flow Diagrams
    - [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
    - OSCAL templates completed when security controls are implemented or modified

### CODE REVIEW

**Review by jasalisbury — COMMENTED** [review]
Looks good overall, I misplace my smarthub tabs in chrome now that the icon has changed! some questions/comments...

1) Should we scroll just the main content so the side nav takes up the whole height of the screen (or is that a bad idea)?
Screenshot from 2021-02-18 09-41-10

2) Is there anything we can do to the side nav to make it more usable at smaller screen widths?

3) Main content is placed in the center of the screen, should we pull it over to the left next to the side nav? Also may help with the activity reports table not showing as full width.

4) The `Activity Reports` link shows as active on every page

**Comment by dcloud** [comment]
> Looks good overall, I misplace my smarthub tabs in chrome now that the icon has changed! some questions/comments...
> 
> 1. Should we scroll just the main content so the side nav takes up the whole height of the screen (or is that a bad idea)?
>    Screenshot from 2021-02-18 09-41-10
> 2. Is there anything we can do to the side nav to make it more usable at smaller screen widths?

Both great questions! I wasn't sure what expectations were around smaller screen sizes or mobile. I probably should have brought that up before requesting reviews, but forgot. Once we get down to smaller widths (say below 1000px), we'd probably want to scale down multiple elements. The Activity Report pages seem designed to take up the full width of the screen, so do we hide the SiteNav and use a menu button, and if so, where would that menu button go? On the [USWDS Header](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/release-2.10.0/components/preview/header--basic.html) everything is set up on the right side of the screen, and for us to do something similar would mean that the menu button would need to be on the left side, which is where the logo/title are. Do we just shift those over to make room for a Menu button?

> 3. Main content is placed in the center of the screen, should we pull it over to the left next to the side nav? Also may help with the activity reports table not showing as full width.

Took me some fiddling, but I see what you mean. At larger widths (> 1300px wide) the grid-container that wraps the main content is centering things. I think you're right, the main content should pull to the left. Will make that change.

> 4. The `Activity Reports` link shows as active on every page

I take it you mean the white border on the left side? I think that should be active for any page in the "Activity Reports" section, right? I'll go ahead and make it active "per-section" though we only have two sections (AR, Admin), at the moment. Also, I assume the bottom links, such as "Admin", should get that white border when active. Does that sound right?

**Comment by jasalisbury** [comment]
> The Activity Report pages seem designed to take up the full width of the screen, so do we hide the SiteNav and use a menu button, and if so, where would that menu button go? On the USWDS Header everything is set up on the right side of the screen, and for us to do something similar would mean that the menu button would need to be on the left side, which is where the logo/title are. Do we just shift those over to make room for a Menu button?

Yeah that is a good question, thoughts @arickalewis1?

> I take it you mean the white border on the left side? I think that should be active for any page in the "Activity Reports" section, right? I'll go ahead and make it active "per-section" though we only have two sections (AR, Admin), at the moment. Also, I assume the bottom links, such as "Admin", should get that white border when active. Does that sound right?

Yea I believe it should be active for any url that starts with `/activity-reports`. I was seeing it as active on the `/admin` page.

**Comment by dcloud** [comment]
Just pushed some changes that should take care of items 3&4 (main content being centered, active links get left border).

**Comment by jasalisbury** [comment]
> Just pushed some changes that should take care of items 3&4 (main content being centered, active links get left border).

Looks good! The change causes the activity report to fill the complete width of the page, we may need to set a max width on the activity report.

**Comment by gopar** [comment]
Not sure if you can add in an easy fix for this? Left nav, doesn't properly go all the way down.
[picture](https://user-images.githubusercontent.com/1545083/108419259-24941280-71e7-11eb-9370-1a7732963a4c.png)

**Review by gopar — APPROVED** [review]

**Comment by dcloud** [comment]
I think we can still discuss:

1. Remediation for small screen sizes (things start look broken at phone-type dimensions)
2. Whether the sidebar should be fixed to the left side and stretch/shrink to the viewport height

**Comment by dcloud** [comment]
After some discussion where we decided that the SiteNav should take up the viewport height and pinned to the side, I made changes to SiteNav.js, App.js and Header.js to absolutely position the SiteNav and Header. I also made an adjustment to the AR reports "sticky" sidenav so it wouldn't scroll offscreen.

**Comment by dcloud** [comment]
I also checked things out in IE11 (running inside a Win8 VM), and the layout changes worked as expected.

**Review by jasalisbury — COMMENTED** [review]
The report page needs a max width but other than that looks good! Let me know if you think we should take care of the report page in a different PR!

Screenshot from 2021-02-23 13-23-30

**Comment by dcloud** [comment]
@jasalisbury Re-added maxw for the content container plus a print-related fix that hadn't gotten pushed earlier today.

**Review by jasalisbury — APPROVED** [review]
:shipit:

**Pull request merged**
