### PR TITLE
submit report for approval

### PR DESCRIPTION
**Pull request by jasalisbury**
**Description of change**

A report can now be submitted for approval. Every page must be "completed" before a report can be submitted. A single manager must be assigned as the approving manager.

**How to test**

1) Pull down and run migrations
2) Fill out a complete report
3) Submit the report, note the review page in navigation is marked "submitted"

Or test it out on [sandbox](https://tta-smarthub-sandbox.app.cloud.gov/)

**Issue(s)**
* https://github.com/HHS/Head-Start-TTADP/issues/135

**Checklist**

- [x] Meets issue criteria
- [x] Code tested
- [x] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [x] Documentation updated
    - API methods
    - Boundary and Data Flow Diagrams
    - [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
    - OSCAL templates completed when security controls are implemented or modified

### CODE REVIEW

**Comment by dcmcand** [comment]
I am testing this, and it looks like it works, but when I am filling out the form, I get an "unable to save form" error, and the logs show `SERVICE:ACTIVITY_REPORTS id: 2 Sequelize error SequelizeDatabaseError: invalid input syntax for type integer: ""`

**Comment by dcmcand** [comment]
Also, it looks like it stays saying submitted even if you go to fill out a new report. If you skip to submit when submitting a second report, it shows this, and you go through the whole second report properly, when you get to the submit stage, it says that it is submitted even before you select an approving manager and press select.
Screenshot from 2021-01-20 13-32-10

**Comment by jasalisbury** [comment]
> I am testing this, and it looks like it works, but when I am filling out the form, I get an "unable to save form" error, and the logs show `SERVICE:ACTIVITY_REPORTS id: 2 Sequelize error SequelizeDatabaseError: invalid input syntax for type integer: ""`
> 
> Edit: Investingation shows this was user error, I had forgot to put a grantee name in.

I think this was an actual bug I just pushed a fix up for. Null approving manager id came across the wire as an empty string `""`

**Comment by jasalisbury** [comment]
> It looks like it stays saying submitted even if you go to fill out a new report.

I think I have the form proper resetting itself, this should be fixed.

**Comment by dcmcand** [comment]
Still seeing the same issue with submitting twice. 
Screenshot from 2021-01-21 13-23-01

**Comment by jasalisbury** [comment]
> Still seeing the same issue with submitting twice.
> 
> My flow is to create the first complete report and then click on Activity Reports in the nav and start again. I also noticed the second time it saves successfully even without a grantee or non-grantee name.
> 
> Screenshot from 2021-01-21 13-23-01

Alright I _think_ I have it nailed down, but let me know if you still see the same issue!

**Review by dcmcand — APPROVED** [review]
Looks good!

**Pull request merged**
