### PR TITLE
Initial basic backend with docker and nodemon

### PR DESCRIPTION
**Pull request by kryswisnaskas**
Very basic initial backend with docker and nodemon.

To test it:

- `npm run docker:start`
- open localhost:3000
- modify src/index.js and enter a different message
- reload localhost:3000 - the message should be updated

### CODE REVIEW

**Comment by jasalisbury** [comment]
Looks good, few questions:
 1. Do we want to add `node_modules` to the `.gitignore` file?
 2. Is the `Dockerfile` file used? Can it be deleted?
 3. Since the frontend will be in this repo as well do we want to put the backend in a separate folder and not the root of the project?

**Comment by kryswisnaskas** [comment]
> Do we want to add node_modules to the .gitignore file?
Not copying node_modules might be faster, although I haven't run timing tests.
> Is the Dockerfile file used? Can it be deleted?
The Dockerfile was meant to be a placeholder with an assumption that we would use it for production deploys. All the needed commands would go there. If we have a different approach we can talk. Maybe @SarahJaine can weigh in from the dev ops perspective

> Since the frontend will be in this repo as well do we want to put the backend in a separate folder and not the root of the project?
What we have now is one of the options for structuring of the entire project. Do you think there a gain to moving the backend to a different folder?

**Comment by jasalisbury** [comment]
> What we have now is one of the options for structuring of the entire project. Do you think there a gain to moving the backend to a different folder?

I think so, would make it easier to keep the `frontend` and `backend` separate (at least in my head!).

**Comment by SarahJaine** [comment]
> > Do we want to add node_modules to the .gitignore file?
>
> Not copying node_modules might be faster, although I haven't run timing tests.

Yes please, I think this is faster. Also I think this makes code reviews cleaner because you don't have node module changes in your diffs.  We all just need to be diligent about updating package.json and yarn.lock :)

> > Is the Dockerfile file used? Can it be deleted?
> 
> The Dockerfile was meant to be a placeholder with an assumption that we would use it for production deploys. All the needed commands would go there. If we have a different approach we can talk. Maybe @SarahJaine can weigh in from the dev ops perspective

I don't have an opinion on this yet. I'm still wrapping my head around what tools make sense in this set up.
 
> > Since the frontend will be in this repo as well do we want to put the backend in a separate folder and not the root of the project?
> 
> What we have now is one of the options for structuring of the entire project. Do you think there a gain to moving the backend to a different folder?

Is the suggestion to create a dir called `backend/`? In monorepos, I thought backend stuff lives at root, and there is usually a dir for the frontend stuff called "website" or something similar. I'm really reaching far into my pre-Ad Hoc memory on this one.  Please correct me if I'm wrong or if this was a habit just particular to my last job.  For some reason, having  a `backend/` dir just seems so wrong.

**Comment by rahearn** [comment]
> I don't have an opinion on this yet. I'm still wrapping my head around what tools make sense in this set up.

Let me know if anyone wants to jump on a call to go over what cloud.gov offers in a bit more depth.

**Comment by SarahJaine** [comment]
> > I don't have an opinion on this yet. I'm still wrapping my head around what tools make sense in this set up.
> 
> Let me know if anyone wants to jump on a call to go over what cloud.gov offers in a bit more depth.

Thanks @rahearn for this offer!  I noticed there is a lot of training info and documentation on cloud.gov. I'd like to dive into that first and see if I have questions before I use up your time. I most likely will :)

**Pull request merged**
