### PR TITLE
Cm fix ci backend tests

### PR DESCRIPTION
**Pull request by dcmcand**
**Description of change**
Fix race conditions in tests.
I found a number of conditions that potential would conflict when running tests in parallel. This included non unique emails, hsesUsernames and names for test users.

**How to test**
Backend tests pass consistently.

I have tested with passing tests 6 times back to back. Hopefully that is enough!

**Checklist**

- [X] Meets issue criteria
- [X] Code tested
- [X] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [X] Documentation updated
    - API methods
    - Boundary and Data Flow Diagrams
    - [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
    - OSCAL templates completed when security controls are implemented or modified

### CODE REVIEW

**Comment by kryswisnaskas** [comment]
Hmm... so far after pulling the branch locally, I am able to run the tests without failure on the first try, but then still get an error.

**Comment by dcmcand** [comment]
> Hmm... so far after pulling the branch locally, I am able to run the tests without failure on the first try, but then still get an error.

What error?

**Comment by kryswisnaskas** [comment]
Found what the issue is. Line 42 in apiDirectory.test.js should be 

`await User.destroy({ where: { id: mockUser.id } });`

**Comment by kryswisnaskas** [comment]
Other than that one change, which appears not to be a part of the PR, the tests run fine and they look good.

**Comment by kryswisnaskas** [comment]
> > Hmm... so far after pulling the branch locally, I am able to run the tests without failure on the first try, but then still get an error.
> 
> What error?

`SequelizeUniqueConstraintError: Validation error`

**Comment by dcmcand** [comment]
I am not getting errors locally. What change do you think needs to happen?

**Comment by kryswisnaskas** [comment]
> I am not getting errors locally. 
That's likely because in docker the db is recreated before each run. 

> What change do you think needs to happen?
Just that one I mentioned above. That's it.

**Comment by dcmcand** [comment]
> > I am not getting errors locally.
> 
> That's likely because in docker the db is recreated before each run.
> 
> > What change do you think needs to happen?
> 
> Just that one I mentioned above. That's it.
I misread that. Just updated it.

**Review by kryswisnaskas — APPROVED** [review]
👍

**Review by gopar — APPROVED** [review]
\o/

**Review by rahearn — APPROVED** [review]

**Pull request merged**
