### PR TITLE
Fix url routing

### PR DESCRIPTION
**Pull request by jasalisbury**
**Description of change**

 * The login button sends the referrer header (note it is actually spelled `referer` in the header, [some backstory](https://stackoverflow.com/questions/3087626/was-the-misspelling-of-the-http-field-name-referer-intentional)) that is used to redirect the user to the proper frontend page after login.
 * Add frontend 404 page (an actual html page)
 * Add backend 404 route (a text response)

**How to test**

1. Without logging in go to `https://tta-smarthub-sandbox.app.cloud.gov/activity-reports` and login. You should be redirected to the activity reports page after login.
2. Go to `https://tta-smarthub-sandbox.app.cloud.gov/test`. You should see a generic 404 page.
3. Go to `https://tta-smarthub-sandbox.app.cloud.gov/api/test`. You should see "Not found" text.

**Issue(s)**
* https://github.com/HHS/Head-Start-TTADP/issues/121

**Checklist**

- [x] Meets issue criteria
- [x] Code tested
- [x] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [n/a] Documentation updated
    - API methods
    - Boundary and Data Flow Diagrams
    - [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
    - OSCAL templates completed when security controls are implemented or modified

### CODE REVIEW

**Comment by SarahJaine** [comment]
@jasalisbury Can you screenshot the "generic 404 page" you get for https://tta-smarthub-sandbox.app.cloud.gov/test?  When I try that page unauthenticated I get a redirect to login (what I'd expect) and when I try it logged in I get the below screen.  Is this what you're expecting? This seems like the page you describe in the third test case.


Screen Shot 2020-11-09 at 11 40 42 AM

**Comment by jasalisbury** [comment]
https://tta-smarthub-sandbox.app.cloud.gov/test
Screenshot from 2020-11-09 12-56-41

https://tta-smarthub-sandbox.app.cloud.gov/api/test
Screenshot from 2020-11-09 12-56-53

**Comment by jasalisbury** [comment]
> @jasalisbury Can you screenshot the "generic 404 page" you get for https://tta-smarthub-sandbox.app.cloud.gov/test? When I try that page unauthenticated I get a redirect to login (what I'd expect) and when I try it logged in I get the below screen. Is this what you're expecting? This seems like the page you describe in the third test case.
> 
> Screen Shot 2020-11-09 at 11 40 42 AM

Yeah I could have worded that better, I posted a comment with the pages you should matched up with their url.

**Comment by jasalisbury** [comment]
Merged main, should be back on sandbox once it is built in circle ci

**Comment by rahearn** [comment]
There seems to be a login issue on sandbox right now but not on dev or sandbox. I'm seeing a pretty consistent `502` app timeout on login if the user had not already been logged into HSES UAT. It seems to work properly if I had already been logged into UAT before hitting the login button on sandbox.

**Comment by jasalisbury** [comment]
> There seems to be a login issue on sandbox right now but not on dev or sandbox. I'm seeing a pretty consistent `502` app timeout on login if the user had not already been logged into HSES UAT. It seems to work properly if I had already been logged into UAT before hitting the login button on sandbox.

The `sameSite=strict` setting was causing the session cookie to not get sent to HSES which caused the session to not have the referrer path set after login at HSES. Setting to `sameSite=lax` fixed the issue. See https://owasp.org/www-community/SameSite

**Review by kryswisnaskas — APPROVED** [review]

**Comment by kryswisnaskas** [comment]
Looks good! 👍 
At some point it would be good to improve the backend branch test coverage, but it is not a blocker for this PR.

**Pull request merged**
