### PR TITLE
CD: Add env variables to application

### PR DESCRIPTION
**Pull request by SarahJaine**
**Description of change**
- Pass env variables to application in deployment pipeline
- Add sandbox: I also added back in the sandbox deployment configuration. I think this could be useful as a way for developers to test changes during feature development. I've found it critical for my work. I added a short explanation of the sandbox environment to the Deployment section of the README.md.
- Give each deployment a unique application name (constructed with `tta-smarthub-((env))` in manifest.yml). Cloud.gov uses the application name to construct the route that serves the application. Only one application can be served at each route, thus necessitating unique application name.

**How to test**
Sandbox application is [deployed](https://app.circleci.com/pipelines/github/adhocteam/Head-Start-TTADP?branch=sj-cd-env-var), cloud.gov [instance is healthy](https://dashboard.fr.cloud.gov/applications/2oBn9LBurIXUNpfmtZCQTCHnxUM/3bbcd330-7908-47b3-b346-6e779f2cd75d/summary), and application is served at https://tta-smarthub-sandbox.app.cloud.gov

**Issue(s)**
* https://github.com/HHS/Head-Start-TTADP/issues/47

**Checklist**

- [x] Meets issue criteria
- [x] Code tested
- [n/a] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [x] Documentation updated - _updated README, added comments_
    - API methods
    - Boundary and Data Flow Diagrams
    - [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
    - OSCAL templates completed when security controls are implemented or modified

### CODE REVIEW

**Comment by kryswisnaskas** [comment]
Nice! The application is deployed! 🎉 (and the instance is healthy)

image

**Review by jasalisbury — APPROVED** [review]

**Comment by kryswisnaskas** [comment]
The log output also looks good. 

Couple of questions/suggestions.

Should we at this point direct the users to the front end instead of the backend api?
As an aside, my HSES login stopped working. I am getting an error (which is not related to this PR). I know the server was reset. Maybe that caused the issue. Are you able log in ok?

Also, should we explore excluding of the test files from the build directory in production mode? 
The test files could be excluded by `--ignore 'src/**/*.test.js'` in the build step.

**Comment by jasalisbury** [comment]
> As an aside, my HSES login stopped working. I am getting an error (which is not related to this PR). I know the server was reset. Maybe that caused the issue. Are you able log in ok?

Your password reset to what it was originally when your account was created. The password is in a thread in slack somewhere. I was able to recreate my account and login. I got an error when logging in `HSES is unable to process the request. (5XX)` which makes sense as all the settings are still for local development. I'm not sure if we will get another set of OAuth creds for the deployed dev environment?

**Comment by kryswisnaskas** [comment]
Thanks. I was just trying the old password, which appears to be working. The accounts must have been reset to the original temp password.

**Comment by kryswisnaskas** [comment]
>  I'm not sure if we will get another set of OAuth creds for the deployed dev environment?

Good question

**Comment by SarahJaine** [comment]
> Couple of questions/suggestions.
> 
> Should we at this point direct the users to the front end instead of the backend api?
> As an aside, my HSES login stopped working. I am getting an error (which is not related to this PR). I know the server was reset. Maybe that caused the issue. Are you able log in ok?
> 
> Also, should we explore excluding of the test files from the build directory in production mode?
> The test files could be excluded by `--ignore 'src/**/*.test.js'` in the build step.

I'm happy to explore those suggestions in a follow up PR if that's okay with you.

**Pull request merged**
