### PR TITLE
Validate API request params

### PR DESCRIPTION
**Pull request by SarahJaine**
## Description of change
Adds middleware to validate request fileIds: reportId (Activity Report pk for delete file file endpoint), activityReportId (Activity Report pk for all other endpoints), and fileId (file pk for delete report endpoint). Also, this sets up a pattern for us to use middleware to validate request params.

from ticket: 

> While investigating TTAHUB-178, we noticed requests with malformed reportId values in the URL were sent to the API and triggering errors on the backend. Essentially, someone could alter a URL in the browser location bar, `http://localhost:3000/activity-reports/1badreportid` and that information would be sent to the backend and the backend would attempt to do a lookup.

## How to test
- Wrote new tests.

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-194

### Every PR

- [x] Meets issue criteria
- [x] JIRA ticket status updated
- [x] Code is meaningfully tested
- [na] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [x] API Documentation updated
- [na] Boundary diagram updated
- [na] Logical Data Model updated
- [na] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Comment by SarahJaine** [comment]
Needed a break from mult approvers, so I put this together. What do you all think of this approach?

**Comment by thewatermethod** [comment]
I think it makes sense to check in principle, and where and how you are checking also makes sense to me.

**Review by jasalisbury — COMMENTED** [review]
I like it! Looks good to me

**Review by thewatermethod — APPROVED** [review]
This is great. Smart to use the callback pattern.

**Pull request merged**
