### PR TITLE
Cm 393 read regions permissions

### PR DESCRIPTION
**Pull request by dcmcand**
**Description of change**
Removes `readRegions` from `req.session`

**How to test**
1. log in as admin and remove site access from a user.
2. Create some reports in that users region.
3. Stop the server and change to the users id
4. open a different browser and try to login
5. stop the server and go back to the admin id
6. in your first browser grant site access to the user
7. stop the server and change to the user's id
8. start the server
9. go to your second browser and refresh
10. Click on `Activity Reports`
11. you should be able to see the reports in that region

**Issue(s)**
* https://github.com/HHS/Head-Start-TTADP/issues/393

**Checklist**

- [X] Meets issue criteria
- [X] Code tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] Documentation updated
    - API methods
    - Boundary and Data Flow Diagrams
    - [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
    - OSCAL templates completed when security controls are implemented or modified

### CODE REVIEW

**Comment by jasalisbury** [comment]
I think if we really want to test this we'd have to use sandbox, with auth bypassed I can't reproduce the issue locally on the main branch.

**Review by jasalisbury — APPROVED** [review]
Code looks good, we should probably test out in sandbox before pushing this PR through

**Comment by dcmcand** [comment]
> I think if we really want to test this we'd have to use sandbox, with auth bypassed I can't reproduce the issue locally on the main branch.

If you want to pair on this real quick, we could do it. I can take away site access for you then give it to you after you try to login.

**Comment by jasalisbury** [comment]
> > I think if we really want to test this we'd have to use sandbox, with auth bypassed I can't reproduce the issue locally on the main branch.
> 
> If you want to pair on this real quick, we could do it. I can take away site access for you then give it to you after you try to login.

We were able to verify this works in sandbox. I logged in without site access/region permissions and was able to view the site and region table without re-login

**Review by rahearn — APPROVED** [review]

**Pull request merged**
