### PR TITLE
Form navigation more consistent

### PR DESCRIPTION
**Pull request by jasalisbury**
**Description of change**
 * Any page navigation saves the form to the API
 * Continue is not blocked by an invalid form
 * If the page is valid on navigation that page is marked as complete
 * Any save with an id of "new" triggers a page reload with the saved activity report's id instead of "new"
 * After visiting the review page validation errors are shown in the form
 * Fixed a bug where report recipients couldn't be removed

**How to test**
1) Pull down changes
2) Create a new report. Click "Continue" without completely filling out the first page, you should navigate to the second page
3) Visit the review page, and back to the first page. You should see required fields marked with errors
4) Completely fill out the first page. Navigate away with the side nav. The state of the first page should be "Complete"

**Issue(s)**
* https://github.com/HHS/Head-Start-TTADP/issues/313

**Checklist**

- [x] Meets issue criteria
- [x] Code tested
- [x] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] Documentation updated
    - API methods
    - Boundary and Data Flow Diagrams
    - [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
    - OSCAL templates completed when security controls are implemented or modified

### CODE REVIEW

**Review by dcmcand — COMMENTED** [review]
This is much nicer to work with. Everything works nicely, however, it will let you click save draft or save and continue when you haven't selected a grantee, which means it won't actually save. You could fill out everything in the report except the grantee, click save draft, and think you were good, then lose all your work by clicking away.

We could require at least a grantee (or non-grantee) to be filled in before they can proceed, or have a temp none grantee that things automatically get saved to if you don't select one. We could then have a check that you can't submit a report with that grantee assigned. There could be better ways to deal with it, but those two come to mind.

**Review by gopar — APPROVED** [review]

**Comment by jasalisbury** [comment]
> This is much nicer to work with. Everything works nicely, however, it will let you click save draft or save and continue when you haven't selected a grantee, which means it won't actually save. You could fill out everything in the report except the grantee, click save draft, and think you were good, then lose all your work by clicking away.
> 
> We could require at least a grantee (or non-grantee) to be filled in before they can proceed, or have a temp none grantee that things automatically get saved to if you don't select one. We could then have a check that you can't submit a report with that grantee assigned. There could be better ways to deal with it, but those two come to mind.

@rahearn thoughts? I can't remember why the report requires a recipient before it is saved as a draft. Might be simplest to drop that requirement if possible and allow any report to be saved as a draft.

**Comment by rahearn** [comment]
> * Any save with an id of "new" triggers a page reload with the saved activity report's id instead of "new"

Does it trigger a full page reload? I'm seeing that currently on main and it's not a good user experience. Can we silently update the URL in the location bar without triggering the reload?

**Comment by rahearn** [comment]
> I can't remember why the report requires a recipient before it is saved as a draft. Might be simplest to drop that requirement if possible and allow any report to be saved as a draft.

Some fields (goals, at least) will require the grantee before they can be properly loaded, but I agree that it'd be best to drop that requirement for MVP. I think longterm maybe there's a better solution where there's an unskippable step one that maybe just asks for the grantee(s) and dates(?) but I'd want you all to do some user research on that before implementing it and we don't have time for that before MVP.

**Comment by jasalisbury** [comment]
> > * Any save with an id of "new" triggers a page reload with the saved activity report's id instead of "new"
> 
> Does it trigger a full page reload? I'm seeing that currently on main and it's not a good user experience. Can we silently update the URL in the location bar without triggering the reload?

Experience should be a lot better now

**Review by rahearn — APPROVED** [review]

**Pull request merged**
