### PR TITLE
Adjust AR Review page layout on smaller screens

### PR DESCRIPTION
**Pull request by dcloud**
**Description of change**

While working on #86, we noticed that the Activity Report Review page looked cramped on smaller screen sizes. This PR makes some adjustments to the layout on smaller screen widths so things are more readable.

- Stack label/values for reviewItems, and adjust font size/weight on labels at small sizes
- Adjust layout of Navigator, Navigator's SideNav for <1024 width screens

**How to test**

Open an Activity Report review page, scale the window to <1024px wide, and see how the layout changes

**Issue(s)**
* https://github.com/HHS/Head-Start-TTADP/issues/318

**Checklist**

- [ ] Meets issue criteria
- [ ] Code tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] Documentation updated
    - API methods
    - Boundary and Data Flow Diagrams
    - [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
    - OSCAL templates completed when security controls are implemented or modified

### CODE REVIEW

**Review by jasalisbury — APPROVED** [review]
:+1: Looks good!

**Review by rahearn — APPROVED** [review]
🎉 

One question I have that doesn't need to prevent merging this: you've moved away from using `<Grid>` in a couple places (both this PR and some others I've seen), is there a particular issue with that component that makes using bare divs better?

**Comment by dcloud** [comment]
> 🎉
> 
> One question I have that doesn't need to prevent merging this: you've moved away from using `<Grid>` in a couple places (both this PR and some others I've seen), is there a particular issue with that component that makes using bare divs better?

I found that it was basically just adding an unnecessary layer of abstraction on top of the USWDS CSS model. I think in an earlier PR I was solving some more complex layout issues and in the course of that realized the `<Grid>` component was just using JS as an abstraction over the CSS classes. It seemed odd to have to add some classes via the className prop and others via breakpoint props. My question was basically the inverse of yours: is there a particular issue with plain HTML and CSS that makes using [`<Grid>`](https://github.com/trussworks/react-uswds/blob/main/src/components/grid/Grid/Grid.tsx) and [`<GridContainer>`](https://github.com/trussworks/react-uswds/blob/main/src/components/grid/GridContainer/GridContainer.tsx) better? And I think the answer is no, these components don't add anything beyond another layer of abstraction.

**Comment by rahearn** [comment]
> My question was basically the inverse of yours: is there a particular issue with plain HTML and CSS that makes using [`<Grid>`](https://github.com/trussworks/react-uswds/blob/main/src/components/grid/Grid/Grid.tsx) and [`<GridContainer>`](https://github.com/trussworks/react-uswds/blob/main/src/components/grid/GridContainer/GridContainer.tsx) better?

Fair enough. I think I come down in the spot where if you're not having to override `className` then using the pre-packaged components make sense, but I definitely see your point of the weirdness of mixing classes and other attributes to massage what you need. Thanks for indulging the question.

**Pull request merged**
