### PR TITLE
Context menu now properly displays

### PR DESCRIPTION
**Pull request by jasalisbury**
**Description of change**
Position absolute will position elements in relation to the neariest positioned ancestor, which before this change was whatever was on the page. Now since the context menu is positioned (with position: relative) the menu will be placed in relation to the context menu wrapper

**How to test**

1) Try to open the context menu while on main, not you can't see the `View` button (I had to resize my window to make the menu not show up)
2) Checkout `js-fix-context-menu`
3) Open the context menu, you can see the `View` button

**Issue(s)**
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-116

**Checklist**

- [ ] Meets issue criteria
- [ ] Code tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] Documentation updated
    - API methods
    - Boundary and Data Flow Diagrams
    - [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
    - OSCAL templates completed when security controls are implemented or modified

### CODE REVIEW

**Comment by gopar** [comment]
Yups, I can see it again, but it's being chopped off (it was always like this right?)
Screen Shot 2021-04-15 at 1 03 36 PM

**Comment by jasalisbury** [comment]
> Yups, I can see it again, but it's being chopped off (it was always like this right?)
> Screen Shot 2021-04-15 at 1 03 36 PM

It might have been, not sure. I'll see if I can figure that one out

**Comment by jasalisbury** [comment]
> > Yups, I can see it again, but it's being chopped off (it was always like this right?)
> > Screen Shot 2021-04-15 at 1 03 36 PM
> 
> It might have been, not sure. I'll see if I can figure that one out

Yeah seems like we can't have the x axis scrollbar with the y axis being overflow visible (https://stackoverflow.com/questions/6421966/css-overflow-x-visible-and-overflow-y-hidden-causing-scrollbar-issue). We'll have to figure out how we want to handle the last element in the table (and maybe the last two once more items make it into the context menu)

**Review by gopar — APPROVED** [review]

**Review by rahearn — APPROVED** [review]
Agree that we need to do something for the last row or two going forward, can you create a new task to track that?

**Comment by jasalisbury** [comment]
> Agree that we need to do something for the last row or two going forward, can you create a new task to track that?

https://ocio-jira.acf.hhs.gov/browse/TTAHUB-117

**Pull request merged**
