### PR TITLE
[no ticket] add next steps to approved activity report view

### PR DESCRIPTION
**Pull request by thewatermethod**
## Description of change

The approved activity report should show specialist and grantee next steps.

## How to test
Visit an approved report page and check that the next steps table appears, near the bottom.

### Every PR

- [n/a] Meets issue criteria
- [n/a] JIRA ticket status updated
- [x] Code is meaningfully tested
- [x] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [n/a] API Documentation updated
- [n/a] Boundary diagram updated
- [n/a] Logical Data Model updated
- [n/a] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Comment by kryswisnaskas** [comment]
Looks good! 👍 Verified that the next steps show for both the specialists and the grantees.

One observation - can we extend the line underlying the activity report number to align with the right side of the table? This way we would support various lengths for the AR number from single digits ids to multiples. If it is too much, we could create a separate PR. Below is a screenshot:

image

**Comment by thewatermethod** [comment]
I can do that pretty easily if it's needed, however that would differ from the design, in which the line under the AR id appears to be independent of the length of either: https://preview.uxpin.com/962c9d405b02aa912e8daf53db2457dccc0998e7#/pages/140432511/simulate/no-panels?mode=i

**Comment by kryswisnaskas** [comment]
Good point - so maybe what we need is to adjust the font size of the AR number and make the line longer and black. What do you think?

This is what I see when looking side by side - top is the design:

image

**Comment by PatricePascual-ACF** [comment]
My two cents on the line under AR: If it can't dynamically fit, I'd prefer the design - that the line be longer than the text.

**Comment by thewatermethod** [comment]
I've knocked the size of the text down slightly, made the line black, and matched it to the width of the tables underneath.

**Comment by PatricePascual-ACF** [comment]
Thanks, @thewatermethod 
@kryswisnaskas, what say you?

**Comment by kryswisnaskas** [comment]
Looks nicer now 👍 Thanks.

**Review by kryswisnaskas — APPROVED** [review]

**Comment by PatricePascual-ACF** [comment]
Thank you both!

**Pull request merged**
