### PR TITLE
[TTAHUB-216] Regional Dashboard: Turn off specific lines on TTA Hours graph

### PR DESCRIPTION
**Pull request by thewatermethod**
## Description of change
Added checkboxes and a button control to toggle the lines drawn on the TTA Hours graph.

## How to test
Visit the Regional Dashboard page at /regional-dashboard

Note that the Total TTA Hours graph now has checkboxes and an apply filters button.

Select and/or deselect specific lines and click the button. The traces drawn on the graph should change to reflect your selections.

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-216

### Every PR

- [X] Meets issue criteria
- [X] JIRA ticket status updated
- [X] Code is meaningfully tested
- [X] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [n/a] API Documentation updated
- [n/a] Boundary diagram updated
- [n/a] Logical Data Model updated
- [n/a] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Review by jasalisbury — APPROVED** [review]
Looks good! I don't know why but having the `apply filters` button feels strange to me. I'm not sure what the difference is between this graph and the one below that also has the `apply filters` button. Maybe get a second opinion on having the `apply filters` button?

**Comment by thewatermethod** [comment]
FYI - this is waiting on accessibility feedback re the apply filters button before merge

**Review by jasalisbury — COMMENTED** [review]
Have a comment and a question:

Points on the legend are not centered
Screenshot from 2021-08-18 14-42-14

Do we want to remove rows from the accessible table when the series is unselected on the graph? I'm leaning no but could really go either way.

**Comment by thewatermethod** [comment]
Good question. I assumed not 🤷. But I'll see if anyone has a different opinion.

**Comment by thewatermethod** [comment]
> Do we want to remove rows from the accessible table when the series is unselected on the graph? I'm leaning no but could really go either way.

Confirmed w/ Angela on Jira that the checkboxes should only change the graph and not the table. 
Also visually centered the markers on the legend line.

**Review by jasalisbury — APPROVED** [review]
:shipit:

**Pull request merged**
