### PR TITLE
[TTAHUB-110][TTAHUB-146]: Filter and Report menus a11y improvements

### PR DESCRIPTION
**Pull request by dcloud**
## Description of change

Various changes to filter and report menus to improve a11y specifically as it relates to keyboard navigation and screen readers.

Both Filter and ReportMenu components were given "menu" roles for the menus. The Filter component was given the "toolbar" role since it is a collection of controls. Event handlers for keyUp events were added to close menus and move focus back to the button that opened the menu.

When filters are added using the Add Filter button, focus is moved to the new filter. Labels for the filter as a whole were adjusted for better readability.

"Phrases" were adjusted on the DateRangePicker so it wouldn't use the words "checkin" or "checkout" in reference to picking start and end dates.

I created an `AriaLiveRegion` that is loaded in the DOM early on so we can have status-type messages read out to screen readers after interactions like applying filters. So when you apply a filter, a message like "1 filter applied" should be announced to the user.

Discussion around various expectations are on [the ticket, TTAHUB-110](https://ocio-jira.acf.hhs.gov/browse/TTAHUB-110). 

## How to test

Use a screenreader such as VoiceOver on macOS to navigate to and into Filter and Report menus using the keyboard. For VoiceOver, the [keyboard navigation](https://support.apple.com/guide/voiceover/navigation-commands-cpvokys04/10/mac/11.0) involves using the [VoiceOver modifier](https://support.apple.com/guide/voiceover/voiceover-modifier-unac048/10/mac/11.0), e.g. `Control-Option-` to navigate a page. Note that **tab navigation is not necessarily the same as screenreader navigation**.

Create, apply, and remove various filters. 

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-110
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-146

### Every PR

- [x] Meets issue criteria
- [x] JIRA ticket status updated
- [x] Code is meaningfully tested
- [x] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Comment by kryswisnaskas** [comment]
Looks good! Most of the acceptance criteria from the tickets work. 👍 

One item that still persists is the filters menu staying open on blur. Interestingly, the "Reports" menu works well.

**Comment by dcloud** [comment]
> Looks good! Most of the acceptance criteria from the tickets work. 👍
> 
> One item that still persists is the filters menu staying open on blur. Interestingly, the "Reports" menu works well.

Hmmm, this could be related to a change, e5ec739, I made to correct the behavior when using screenreader (VoiceOver). I had observed the menu closing prematurely when navigating between components inside the menu. I had not observed the menu staying open on blur when navigating via tab navigation, however.

@kryswisnaskas did you see this when using tab navigation, screenreader navigation, or mouse navigation? Also if you could provide information on which browser(s) you saw this behavior in, that would be helpful.

**Comment by kryswisnaskas** [comment]
> @kryswisnaskas did you see this when using tab navigation, screenreader navigation, or mouse navigation? Also if you could provide information on which browser(s) you saw this behavior in, that would be helpful.

I saw this in Chrome when clicking outside of the filters menu. The reports work well and I just double checked using the tab key. When using the tab key, both filters and reports work.

**Comment by dcloud** [comment]
Hmmm, looks like a fix for keeping things open when navigating between menu items using (VoiceOver) screen reader is in conflict with the click outside behavior. Basically `e.relatedTarget` can be null (in a focus event object) when navigating between items using VoiceOver or when using mouse clicks. I may need to add logic to some click handlers.

**Review by kryswisnaskas — APPROVED** [review]
Looks good! 👍

**Pull request merged**
