### PR TITLE
Browser nav fix and various IE 11 fixes

### PR DESCRIPTION
**Pull request by jasalisbury**
**Description of change**
 * Push nav state instead of replace on navigation. This means the back/forward browser buttons work
 * Goal picker sets height = min height for the controller, this makes the text inside the textbox center properly in IE 11
 * react-uswds ^1.12.2 was causing the page to not load in IE 11. Downgrade to 1.11.0
 * Hex colors with transparency weren't playing nice with IE 11, converted to rgba
 * Padding-inline wasn't working in IE 11, switch to padding-left
 * Duration validation updated to actually force durations rounded to the half hour
 * Goal multiselect only displays "x goals selected" if there is no user input
 * Objectives are only focused on mount instead of when the ref changes. Fixes a bug where focus switches back to the objective after switching off

**How to test**

1) Pull down changes
2) Navigate using the back/forward buttons
3) Open the site in IE 11

**Issue(s)**
* https://github.com/HHS/Head-Start-TTADP/issues/152

**Checklist**

- [x] Meets issue criteria
- [x] Code tested
- [x] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] Documentation updated
    - API methods
    - Boundary and Data Flow Diagrams
    - [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
    - OSCAL templates completed when security controls are implemented or modified

### CODE REVIEW

**Review by gopar — APPROVED** [review]

**Review by kryswisnaskas — APPROVED** [review]
Looks good!

**Comment by jasalisbury** [comment]
> I won't be able to test this in IE11 until it's on cloud.gov, but the code looks good and it works well in Chrome
> 
> Your choice whether you want to deploy it to sandbox or I can test it on dev after this is merged.

Building and deploying to sandbox now

**Comment by rahearn** [comment]
I found a display bug in Chrome as well.

Screen Shot 2021-03-09 at 8 35 22 PM

**Comment by jasalisbury** [comment]
> It _looks_ good in IE, but I'm seeing some very weird behavior.
> 
> 1. I walked through a whole new report in IE11, filled in every required field, and then didn't submit.
> 2. I then went back to the activity reports list and nothing is showing up.
> 3. I directly went to the report URL, and the topics, resources, and uploaded files are all missing.
> 4. I logged into sandbox in Chrome, and the report properly shows up in the main list and alerts list
> 5. Visiting the report, the topics and resources are still missing, but now the uploaded file is showing up.

I just pushed up a change using the IE 11 version of react hook form. I wasn't able to reproduce what you saw locally or in sandbox, but can you see if using IE 11 `react-hook-form` causes your issues to go away?

**Comment by jasalisbury** [comment]
> I found a display bug in Chrome as well.
> 
> Screen Shot 2021-03-09 at 8 35 22 PM

This was caused by the `height` fix I tried to add for IE 11. I have removed the fix as I look for a better solution for IE 11

**Review by rahearn — APPROVED** [review]
🎉 🚀 🚢

**Pull request merged**
